README.md, git-cliff/src/args.rs, git-cliff/src/lib.rs
Change the way `git-cliff` sorts commit messages on CHANGELOG.md.
Normally, I would expect the latest change on the top in CHANGELOG. However, currently, `git-cliff` puts the oldest commit on the top of the sections(#Features, Fixes and such). 
I tested this using both a mock repo and `git-cliff`'s own repo. 
```
- Support parsing the missing scopes with `default_scope` (#8)
- Support generating a changelog scoped to a directory (#11)
```
With this update, it will look like this:
```
- Support generating a changelog scoped to a directory (#11)
- Support parsing the missing scopes with `default_scope` (#8)
```
=> Put newest commit on top in CHANGELOG.md

.github/workflows/ci.yml, README.md, git-cliff-core/src/commit.rs, git-cliff-core/src/config.rs, git-cliff-core/tests/integration_test.rs, git-cliff/src/changelog.rs
Allow parsing and extraction of links in commit messages.
See #41
Added unit and integration tests.
I also tested it against the history of an internal project.
=> feat(changelog): add `link_parsers` for parsing/extracting links

Cargo.lock, git-cliff-core/Cargo.toml, git-cliff-core/src/commit.rs, git-cliff-core/src/config.rs, git-cliff-core/src/release.rs
Makes `serde` usage more unified across the project thanks to the `derive` feature
=> refactor(lib): unify serde and serde_derive using derive feature

.github/fixtures/cliff.toml, .github/fixtures/expected.md, CHANGELOG.md, README.md, config/cliff.toml, examples/detailed.toml, examples/keepachangelog.toml, examples/scoped.toml, examples/scopesorted.toml, examples/unconventional.toml
Resolves #60
- Comply with [MD022](https://github.com/DavidAnson/markdownlint/blob/v0.25.1/doc/Rules.md#md022)
- Fix minor typos
See #60.
I checked with `grep`.
None
=> style(changelog): comply with MD022 and fix minor typos

codecov.yml
I updated this file because the default branch is `main`, not `master`.
=> fix(project): use the correct branch for codecov

git-cliff-core/src/release.rs
I copied this from [here](https://github.com/rust-lang/git2-rs/blob/0443adb5388b2a529c042256e7716c36dc567220/src/time.rs#L32), which is the function `git-cliff` calls to populate that field.
=> docs(core): document timestamp format of `Release` struct

.github/actions/run-fixtures-test/action.yml, .github/workflows/ci.yml, rust-toolchain.toml
Rust nightly build was fixed:
* https://github.com/briansmith/ring/issues/1469
* https://github.com/rust-lang/rust/issues/95267
* https://github.com/rust-lang/rust/pull/95390
=> chore(ci): return to nightly builds

README.md
Ref: https://github.com/orhun/git-cliff/issues/77#issuecomment-1090552243
Document few more examples of using `git.commit_preprocessors` in git-cliff's TOML config.
https://github.com/kaushalmodi/ox-hugo/blob/2ba8a365c9022b9918d6c65bed9ce35f6c113920/doc/cliff.toml#L56-L68
=> docs(readme): add more regex examples for commit_preprocessors

README.md
Is this backwards?
I thought the sort orders were backwards.
It's a readme.
=> docs(readme): switch chronological and topological

.github/workflows/ci.yml
Update CI workflow for switching to [cargo-tarpaulin](https://github.com/xd009642/tarpaulin)
CI sometimes fails due to `grcov`.
\-
\-
=> chore(ci): switch to cargo-tarpaulin for measuring code coverage

git-cliff/src/lib.rs
Fixes a panic which occurs when the commit limit set in the config is greater than the number of commits.
=> fix(config): set max of `limit_commits` to the number of commits

git-cliff-core/src/config.rs, website/docs/configuration.md
Behavior related to overriding configuration for nested elements via environment variables changed in config-rs@v0.9. We need to use `__` instead of `_` separator to match nested fields. For details see https://github.com/mehcode/config-rs/issues/73. 
Also added some documentation that mentions it's possible to use environment variables to override configuration.
All tests are passing locally, I updated `config::test::parse_config` and added a couple more env override assertions. I also tested in a small sandbox project and observed the following:
history
```
commit 9d5ce9759e2fbedc48fbb23e22cdad74214c809a (HEAD -> main, tag: v1.0.3-rc1)
Author: Mack Solomon <macksol@gmail.com>
Date:   Tue Apr 18 22:14:30 2023 -0700
feat(all): a feature
commit f5b5135793de7bacfdec9750ef9d535320aaa614 …
```
=> fix(config)!: nested environment config overrides

.github/workflows/ci.yml, git-cliff-core/Cargo.toml, git-cliff-core/src/commit.rs, git-cliff-core/src/error.rs, git-cliff-core/src/lib.rs
Make git2 optional in git-cliff-core crate.
In release-plz I use git-cliff-core.
However, I don't need git-cliff to read the git history, so I don't need it to include git2.
I depend on both cargo and git-cliff, and often they have conflicting git2 versions.
For example, right now I can't update to the latest git-cliff, because git2 of git-cliff isn't compatible with cargo.
However with this change, by using:
`git-cliff-core =  { path = "../git-cliff/git-cliff-core", default-features = false }`
in release-plz I'm able to update!
Some questions for you:
- are you ok with this additional complexity?
- do you want to find a better name for the feature?
Probably there are other dependencies that can be made optional, but for now git2 is the biggest pain-point for me.
If you are interested, I …
=> chore(core): make git2 optional

git-cliff-core/src/changelog.rs
This PR adds test cases for the `docs:` prefix.
The current test suite doesn't test the  `docs:` prefix which is the recommended value for documentation commits for conventional commits. This change adds the relevant test cases.
Closes https://github.com/orhun/git-cliff/issues/164
Test cases that were referring `doc:` were duplicated with `docs:` instead.
=> test(changelog): add cases for `docs:` prefix

.github/fixtures/test-commit-footers/cliff.toml, .github/fixtures/test-commit-preprocessors/cliff.toml, .github/fixtures/test-custom-scope/cliff.toml, .github/fixtures/test-date-order/cliff.toml, .github/fixtures/test-ignore-tags/cliff.toml, .github/fixtures/test-keep-a-changelog-links/cliff.toml, .github/fixtures/test-latest-with-one-tag/cliff.toml, .github/fixtures/test-limit-commits/cliff.toml, .github/fixtures/test-skip-breaking-changes/cliff.toml, .github/fixtures/test-split-commits/cliff.toml, .github/fixtures/test-topo-order-arg/cliff.toml, .github/fixtures/test-topo-order/cliff.toml, cliff.toml, config/cliff.toml, examples/cocogitto.toml, examples/detailed.toml, examples/keepachangelog.toml, examples/limitedcommits.toml, examples/minimal.toml, examples/scoped.toml, examples/scopesorted.toml, examples/unconventional.toml, website/docs/templating/syntax.md
The Tera website changed from Netlify to GitHub Pages, with the old Netlify deployment gone. Therefore, all links to Tera should point to the new URL.
Clicked each link, especially the ones with anchors, and verified the anchors are still correct.
=> docs: update Tera links to the new URL

Cargo.lock, git-cliff/Cargo.toml, git-cliff/src/args.rs, git-cliff/src/bin/completions.rs, git-cliff/src/lib.rs
- revert: feat(args): update clap and clap extras to v4 (#137)
- chore: update to clap 4.4.4
This reverts the changes in https://github.com/orhun/git-cliff/pull/292 which downgraded clap to v3 to remove the GPL code.
This is a clean upgrade to the latest version of clap that avoids the GPL licensed code changes in the previous commit.
`git-cliff -h` produces the same output as `cargo run -- -h`
=> chore: remove GPL code

Cargo.lock, git-cliff-core/Cargo.toml, git-cliff-core/src/error.rs, git-cliff-core/src/release.rs, git-cliff/src/args.rs, git-cliff/src/lib.rs, website/docs/usage/examples.md, website/docs/usage/usage.md
`git-cliff` will automatically bump the version for your unreleased changes in the changelog.
For example, if you have `1.0.0` and committed "feat: xyz", `git-cliff --bump --unreleased` will create a changelog for `1.1.0`.
Closes #163
Unit tests.
=> feat(changelog): support bumping the semantic version via `--bump`

git-cliff-core/src/changelog.rs, git-cliff-core/src/commit.rs, git-cliff-core/src/config.rs, git-cliff-core/src/error.rs, git-cliff-core/tests/integration_test.rs, website/docs/configuration.md
This PR introduces the capability of grouping commits by attributes of the commit, i.e. `author.name` or `author.email`. 
This changeset should cover the scenario described in #194.
The reporter of that issue wanted to create a new group based gathering the commits for a specific author name:
```
{ author.name = "Renovate Bot", group = "Dependency Updates"},
```
In order to test it works, I've modified the `cliff.toml` file in this project to include a new group like this:
```
commit_parsers = [
{ field = "author.name", pattern="dependabot\\[bot\\]", group = "Dependency Updates"},
...
```
which generates the following new group:
```
- *(deps)* Bump regex from 1.9.6 to 1.10.0 ([#308](https://github.com/orhun/git-cliff/issues/308)) - …
```
=> feat(config): add field and value matchers to the commit parser

.github/workflows/cd.yml, CHANGELOG.md, cliff.toml, release.sh
fixes #310
Fix the typos in the changelog and automate typos correction in the changelog generation.
#310
On my machine at the moment. I expect the next release to reveal if it breaks or not. Note that `release.sh` will now depend on `typos` being installed on the machine. Not sure if I should document that somewhere.
=> docs(changelog): fix typos

.github/workflows/ci.yml, Dockerfile, README.md, typos.toml, website/docs/templating/context.md
resolves #311
Will catch most of the typos in the documentation and markdown files automatically in CI (see #311 for details). Note that I chose to not create a new job and make it part of the `check` job (but I can go either way).
Also, I configured `typos` to ignore a bunch of 7-chars commit hash and one of your other project `halp` (which obviously is a typo of `help` :upside_down_face:).
See #311.
CI will tell.
=> feat(ci): add 'typos' check

git-cliff-core/src/commit.rs, website/docs/templating/context.md
This PR adds `merge_commit` flag to the context as follows:
```json
{
"id": "ac01f822dd982513433f21b7611c6ef03cc978b0",
"message": "Merge branch 'other'",
"body": null,
"footers": [],
"group": "⚙️ Miscellaneous Tasks",
"breaking_description": null,
"breaking": false,
"scope": null,
"links": [],
"author": {
"name": "Orhun Parmaksız",
"email": "orhunparmaksiz@gmail.com",
"timestamp": 1702757837
},
"committer": {
"name": "Orhun Parmaksız",
"email": "orhunparmaksiz@gmail.com",
"timestamp": 1702760672
},
"conventional": true,
"merge_commit": true // <--
},
```
This can be used to filter out merge commits as follows:
```jinja2
{% for group, commits in commits |
filter(attribute="merge_commit", value=false) |
group_by(attribute="group") %}
{% for commit in commits %}
- {% if commit.breaking …
```
=> feat(commit): add merge_commit flag to the context

git-cliff-core/src/changelog.rs, git-cliff-core/src/commit.rs, git-cliff-core/src/config.rs, git-cliff-core/tests/integration_test.rs, website/docs/configuration.md
See #382
This PR makes it possible to use the SHA1 of a commit with `commit_parsers`.
For example:
```toml
commit_parsers = [
{ sha = "f6f2472bdf0bbb5f9fcaf2d72c1fa9f98f772bb2", skip = true }
]
```
Another example:
```toml
commit_parsers = [
{ sha = "f6f2472bdf0bbb5f9fcaf2d72c1fa9f98f772bb2", group = "Stuff" }
]
```
Unit/integration tests.
I didn't add fixture tests since it requires more work to find out the SHA1 of the created commit and substitue in `expected.md`.
=> feat(parser): support using SHA1 of the commit

git-cliff-core/src/release.rs
When the commit message ends with a '\n', then it is not considered a valid conventional commit. That's why the message must be cleaned up.
Wrong next version when using the bumped-version parameter. The 'git commit' command creates a '\n' at the end of the line.
In this case, commit is considered as a patch. 
[https://github.com/MarcoIeni/release-plz/blob/4b0684ff8d9048032167a43fd70b70af4940239d/crates/next_version/src/next_version.rs#L27](https://github.com/MarcoIeni/release-plz/blob/4b0684ff8d9048032167a43fd70b70af4940239d/crates/next_version/src/next_version.rs#L27)
```
/// - If some commits are present, but none of them match conventional commits specification,
///   the version is incremented as a Patch.
```
git cli command on linux/macos
=> fix(commit): trim the trailing newline from message

git-cliff-core/src/changelog.rs, git-cliff/src/lib.rs
This is a behavior change to improve the `--bump` functionality.
`--bump` flag now takes the processed commits into account which means e.g. if you have used `commit_preprocessors` to modify the commit message, the bumped version will be calculated based on these modified commit messages.
There is also another behavioral change in the `--bumped-version`. For multiple repositories, it used to return the each calculated version separated by newline. However, this functionality is not documented anywhere and I'm not sure if it is really useful. This feature is not released yet which means it was safe to remove. I might consider adding it again if there will be desire in the future.
See #405
Unit tests.
=> refactor(changelog): support `--bump` for processed releases

git-cliff-core/src/repo.rs
closes #188
closes #38
Commit a1b4b5b ("fix(git): sort the commits in topological order"), changed the order from `TIME` to `TIME | TOPOLOGICAL`. According to the docs, this is equivalent to `git log --date-sort`:
* https://github.com/libgit2/libgit2/blob/v1.7.1/include/git2/revwalk.h#L33-L38
This breaks down in the following scenario:
1. A PR is open.
2. A release v1 is made.
3. A PR is merged.
4. A relase v2 is made.
The git history for this would be:
```
- v2 release
- pr merge commit
- v1 release
- actual pr commit
```
This directly spills into the changelog produced by `git-cliff`, misattributing commits that were merged in v2 to v1 retroactively when v2 is made.
You can see this with `git log`. If you pass `--topo-order` there:
```
- v2 relase
- pr merge commit
- actual pr commit
- …
```
=> fix(git): sort commits in topological order

examples/github-keepachangelog.toml, examples/github.toml, git-cliff-core/src/github.rs, git-cliff-core/src/release.rs, website/docs/integration/github.md
This PR makes it possible to use the pull request title with the [GitHub integration](https://git-cliff.org/docs/integration/github):
```jinja2
* {{ commit.github.pr_title }}
```
The final context is the following:
```json
"github": {
"username": "orhun",
"pr_title": "some things have changed",
"pr_number": 420,
"is_first_time": false
}
```
#148
Locally / Fixture tests
=> feat(template): support using PR title in the GitHub template

website/docusaurus.config.js
Commit 1da7cac7ce5df4de0a49ddbb9a52621ffa849124 added Sponsor and GitHub links to the navigation bar. However, the links are not for this project.
This PR fixes these two links.
=> chore(website): fix URLs in navigation bar

website/docs/tips-and-tricks.md
Emojis are hard. The pattern was not matching the certain emojis.
The new pattern fixes the issue by adding the variation selector`u{FE0F}`.
Further, this makes the zero-width joiner (`u{200D}`) optional, matching emojis both with and without the ZWJ.
I tested the new pattern on my repo and found out many commits had been skipped: https://github.com/welpo/tabi/commit/1bb3c91b91585bb6317ed0d82e6d0c0fbc36e0b6
=> docs(website): improve matching gitmoji tip

git-cliff-core/src/github.rs, website/docs/integration/github.md
You can now use `GITHUB_API_URL` if you want to override the GitHub API URL.
closes #508
Locally.
=> feat(github): support overriding the GitHub API URL

git-cliff-core/src/command.rs
This PR fixes #531 where the environment variables were not being passed to cmd on Windows. 
It breaks some of the functionality of being able to run custom shell commands in the preprocessor.
I've tested to verify that when using the COMMIT_SHA environment variable in the traditional cmd fashion ```%COMMIT_SHA%``` that it is now properly available to shell commands.
Tested on Windows 11.
=> fix(command): add missing environment variables for Windows

.github/workflows/cd.yml, npm/git-cliff/package.json, npm/package.json.tmpl
I wouldn't call myself a Bash legend but I think this does the trick. FWIW I tested it using a Bash session, but I can't say for 100% certain the `""` wrapping around the injected value from the GitHub workflow steps is correct, or if GitHub now adds double double quotes (as in `if [ ""true"" = "true" ]`). 
As for the change on line 252, that's mostly just cleaned and moved to `package.json.tmpl`. Note that the binaries cannot be published with `yarn npm publish` because that package.json doesn't reside in a yarn configured folder and we probably don't want that anyway.
I looked at the history for `npm/git-cliff/package.json` and found this commit: https://github.com/orhun/git-cliff/commit/42180437c709f10b9ed5efb8f5cc1595efb3aec7#diff-09031284f88e0ed62cdbc8693d473bf5b8b9c5674257763d8d8ca0c …
=> chore(npm): publish rc version for prereleases

git-cliff/Cargo.toml, pypi/.gitignore, pypi/pyproject.toml
I've updated the maturin version, addressed a deprecation warning, and added a .gitignore file to the pypi folder to ignore files that are generated during build and local testing.
I discovered that the version of maturin specified in `pyproject.toml` was too narrowly constrained in the process of investigating https://github.com/orhun/git-cliff/issues/534.
I ran the `maturin build` command that is normally run in GHA locally, and confirmed that it builds an installable wheel on my platform (Windows).
=> chore(pypi): update maturin version

release.sh
While creating releases locally I followed the directions from `release.sh` to run `cargo install typos` but I'm pretty sure that the correct command is `cargo install typos-cli`.
=> fix(release): fix typo in the installation of typos-cli

website/docs/usage/monorepos.md
Related to #48
`--include-path` with the previous documentation always gave no result. This fixes it by properly documenting the excepted inputs.
On a real project by running the commands
=> docs(website): fix the documentation for `--include-path`

git-cliff-core/src/commit.rs
This PR changes the commit parser behavior to always trim the text (commit message, body, etc.) before matching it with a regex.
This means that you will be able to use `$` in the regex for matching until the end.
closes #554
Locally / tests / fixtures.
=> fix(commit): trim the text before matching with commit parser

.github/workflows/cd.yml, .github/workflows/ci.yml, npm/git-cliff/package.json, npm/git-cliff/yarn.lock, release.sh
fixes #591, I think I broke this in #528 because `yarn npm publish` works differently with which files it includes in the tarball from `npm publish` (which just includes everything from the cwd)
I also added a `cp` of the `CHANGELOG.md` file, because Yarn likes to include that automatically, just like the README. They _used_ to also show it on the package pages before the redesign (ex: https://v3.yarnpkg.com/package/@sapphire/framework) so I can only assume it will be added back eventually.
Emergency fix, as the current release on npm is broken.
I ran the `cd` commands locally:
```sh
yarn install
yarn build
cp ../../README.md .
cp ../../CHANGELOG.md .
yarn pack --dry-run
```
The only differing factor here being the last command because obviously I do not want to actually publish but this …
=> fix(npm): include the proper files in the npm tarball

git-cliff-core/src/commit.rs, website/docs/tips-and-tricks.md
This PR updates the commit parsing to matching empty commit body.
Makes it possible to skip commits with empty body:
```toml
[git]
commit_parsers = [
{ body = "$^", skip = true },
]
```
closes #604
Locally.
=> fix(parser): allow matching empty commit body

git-cliff-core/src/changelog.rs
Prevent duplication of changelog when using `split_commit` and the commits have empty lines.
When using split commits, if there is a an empty line between commits, it will duplicate the commit prior to the empty line, and I noticed that it will sometimes assign it to a different scope, though I have not investigated the why at this point.
One of the reasons this is a problem is that in certain GUIs (like GitHub Desktop) if you enter the first line in the header and the second line in the body, it will automatically add a new line.
fixes #606 
Using the existing test (changelog_generator_split_commits) by adding a new line in one of the commits.
=> fix(changelog): ignore empty lines when using `split_commits`

CONTRIBUTING.md, Cargo.lock, git-cliff-core/Cargo.toml, git-cliff-core/src/changelog.rs, git-cliff-core/src/template.rs
This allows to add custom context from the users of `git_cliff_core`.
I need this in release-plz to inject the crate name in the changelog.
I protyped this in https://github.com/MarcoIeni/release-plz/pull/1399
I guess other people would benefit from this kind of feature as well :)
Locally on the branch I showed you.
Not sure if you want to add the method `add_context` (or a similar approach) to the `Changelog` struct.
Lmk if you prefer to inject the context in another way 👍
https://github.com/MarcoIeni/release-plz/issues/916#issuecomment-2058297612
It contains multiple changelog updates (one for each package) in the same changelog file 🤯
=> feat(changelog): allow adding custom context

git-cliff-core/src/repo.rs
Don't check if last commit is conventional.
Having the PR checks failing because one of the commits is not conventional is annoying for contributors. Original feedback: https://github.com/orhun/git-cliff/pull/613#issuecomment-2059908791
I pushed [fc58c87](https://github.com/orhun/git-cliff/pull/619/commits/fc58c87bf2e6592a31d7f3f60e19d99fa7aabfe8) to this PR. It's not a conventional commit and the tests still work.
=> chore(tests): don't check last commit

npm/git-cliff/package.json, website/docs/installation/npm.md
Resolves #602 by adding `engines` to `npm` package for the minimum supported versions of Node and adds those to the website page about `npm`
Makes system dependencies clearer.
Followed the process I documented on [this comment](https://github.com/orhun/git-cliff/issues/602#issuecomment-2068283185) to find the versions that worked
=> chore(npm): add minimum supported Node versions

git-cliff/src/lib.rs
Using `-` for `stdout` is a common convention between CLI tools and this PR simply adds this support to `git-cliff`.
This makes it possible to use `git-cliff` as follows:
```
$ git-cliff -o -
```
(instead of `git-cliff -o /dev/stdout` or `git-cliff -o`)
Also you can combine it with `-p` as mentioned in #643
Locally
=> feat(output): support using stdout via dash (`-o -`)

git-cliff/src/lib.rs, website/docs/usage/examples.md
setting prepend and output together will ignore the prepend flag
- preprend and output flags are conflicting and should only be used together if they point to different paths
https://github.com/orhun/git-cliff-action/issues/21#issuecomment-2130022787
I build it locally and tested it with one of my rust projects
not sure
=> fix(args): allow -o and -p together if they point to different files

git-cliff-core/src/changelog.rs
This PR updates the changelog processing order to make remote data (e.g. GitHub commits, pull requests, etc.) available in the context.
```
git cliff --github-repo orhun/git-cliff -c examples/github.toml -x --no-exec -u
```
This command will now contain the GitHub data such as:
```json
"github": {
"contributors": [
{
"username": "bukowa",
"pr_title": "style(lint): fix formatting",
"pr_number": 702,
"pr_labels": [],
"is_first_time": true
},
],
}
```
Might fix #687 
Locally.
=> feat(changelog): make remote data available in context

.github/fixtures/test-fixtures-locally.sh
Fixes https://github.com/orhun/git-cliff/issues/705
See issue.
Locally.
=> fix(fixture): support running fixtures on mingw64

git-cliff-core/src/repo.rs
Support for tag messages was added in 3eb828e69ad3a5b94833f67dfe287e7d8b31a274. The commit contains code for stripping GPG signatures from the tag message, but git [supports SSH signatures and x509 signatures as well](https://git-scm.com/docs/gitformat-signature#_description).
This PR adds support for stripping those signature types.
The regex is not 100% accurate (e.g. this would allow `SSH MESSAGE`, which is not part of the gitformat-signature description), but I prioritized readability over correctness in this case (since the code is for replacing text, not verifying the signature).
Signatures should not show up in the changelog, regardless of what kind of signature was used.
I have no x509 certificates, but I [created a SSH-signed tag in my …
=> feat(changelog): skip ssh and x509 signatures in tag messages

Cargo.lock, git-cliff-core/Cargo.toml, git-cliff-core/src/remote/gitlab.rs, website/docs/integration/gitlab.md
Gitlab requires that the project path be fully encoded. See the docs for details. https://docs.gitlab.com/ee/api/rest/#namespaced-path-encoding Pulls in the url encoding crate here. Might not be needed when you have the choice to just update the documentation. I don't think the end user should be required to url encode their own strings. It might be nicer to just add the subgroup paradigm to the gitlab config in general for the future. This will fix the problem for now.
I want to use git cliff on my self hosted gitlab.
https://github.com/orhun/git-cliff/issues/687
I wrote a test. Doesn't cover the case on IF the end user url encodes their own string. This will break unexpectedly, but I rushed this in.
=> fix(gitlab): URL-encode the owner in remote requests for GitLab

config/cliff.toml
This PR changes the comment of the `header` field in the default `cliff.toml` config, from `# template for the changelog footer` to `# template for the changelog header`.
That field is for headers so `footer` in the comment seems to be a typo.
As a change to comments, no tests are required.
=> docs(config): fix typo in comment of default config file

git-cliff-core/src/changelog.rs, git-cliff-core/src/config.rs, git-cliff-core/src/repo.rs, git-cliff/src/lib.rs
Before this change the only way of activating a remote integration (and fetching remote data) used to be incorporating the related variables in a template.
This meant that the changelog context won't contain e.g. GitHub related fields unless you use e.g. `github.contributors` in your template.
This PR adds support for enabling the remote integration for the following cases as well:
- If the `[remote]` table is configured.
- If remote is set via command-line arguments (e.g. `--github-repo`)
So the following output will contain GitHub variables even with the default template (since the remote is set):
```sh
$ git cliff --context --github-repo orhun/git-cliff
```
closes #780
Unit tests, local run.
=> feat(remote): activate integration if remote is set manually

Cargo.lock, git-cliff-core/Cargo.toml, git-cliff-core/src/repo.rs, git-cliff/src/lib.rs
This caches the commit retain checks whenever include/exclude paths are specified.
This speeds up changelog generation by `258` times in a big repository I have:
```
Now: 0.080 s
Before:  20.633 s
```
Fixes #767 
It also improves handling including/excluding patterns, considering the first commit, and various other improvements.
I tested this on the repository mentioned in #767
Here are the profiling flamegraphs created via #768. The bottleneck is removed after this fix is applied as seen in the above image (4366 samples to only 16 samples). After the fix, other parts of the code finally show up in the profiler.
After - Fully Cached:
After - Cached + new commit:
Before:
=> perf(changelog): cache commit retain checks (258 times faster generation)

git-cliff-core/src/config.rs, git-cliff-core/src/release.rs, git-cliff/src/lib.rs
=> fix(changelog): allow using `--bumped-version` without conventional commits

README.md
This PR removes additional characters between each badge.
Underscored spaces don't look very nice.
_See also: [Explanation on why the browser emits extra whitespaces for `<a href="..."><img>` sequences with linebreaks](https://stackoverflow.com/a/65645230)_
Browser.
*Before PR*
*After PR*
=> docs(readme): remove underscored spaces between badges

git-cliff-core/src/template.rs
Tobias Bieniek on [Mastodon](https://hachyderm.io/@tb/113012369376683372) reported that even when he used the GitHub-related template variables [in this comment](https://github.com/orhun/git-cliff/issues/461#issuecomment-1913595602), `git-cliff` wasn't querying GitHub.
The problem turned out to be in the AST parsing. It was simply not taking for-loop arguments into account.
Fixes the issue that mentioned above.
Locally.
=> fix(template): include for-loop arguments in template variables

Cargo.lock, Cargo.toml, git-cliff-core/Cargo.toml, git-cliff/Cargo.toml, git-cliff/src/args.rs
The cli argument `--gitlab-repo` is split at `/` and the last two parts are used as `owner` and `repo`. This PR changes this behavior, splits at the right most `/` and takes the first part as `owner` and the second part as `repo`.
| |raw string|owner|repo|
|--|--|--|--|
|before| `gitlab/group/a/repo_name` | `a` | `repo_name` |
|after this PR| `gitlab/group/a/repo_name` | `gitlab/group/a` | `repo_name` |
GitLab allows projects to be organized in groups. Groups can also be part of groups. Because of that projects are not identified by `owner` and `repo`, but by `group/path` and `repo`.
The same behavior can be achieved by using the following inside the config:
```
[remote.gitlab]
owner = "gitlab/group/a"
repo = "repo_name"
```
But since I would like to use the same config in multiple …
=> feat(args): allow GitLab groups with `--gitlab-repo`

git-cliff-core/src/changelog.rs, git-cliff/src/lib.rs
closes orhun/git-cliff/issues/819
A method is added that only adds the additional context `remote` inside the `Changelog` struct and does not query commit information.
see issue orhun/git-cliff/issues/819
I created a changelog and checked that the Gitlab PR information are not changed.
=> fix(changelog): don't change the context when provided via `--from-context`

cliff.toml
This pull request removes the usage of `{% raw %}` and `{% endraw %}` tags from the template files. The presence of these tags caused parsing issues for higher-level callers that also utilize the Jinja engine.
The change is necessary because using `{% raw %}` and `{% endraw %}` tags can interfere with the correct parsing of templates by higher-level callers using the Jinja engine. This modification ensures compatibility and proper parsing for all Jinja-based template users. This PR addresses an issue where templates could not be parsed correctly due to the conflict caused by these tags.
closes #818
Tested.
N/A
=> fix(template): resolve parsing issues with `raw`/`endraw` in Jinja

git-cliff/src/lib.rs
sync use_branch_tags from config to args
i oversighted in #808. the command line argument works but not from the configuration
=> fix(args): support using use_branch_tags from both config and args

CONTRIBUTING.md
Mention in the CONTRIBUTING.md file that tags are necessary for running tests successfully. 
I wanted to contribute to the project, but when I followed the instructions on the contributing page, I didn't realize that some tests required tags in the repositories. When I forked the repository, the tags were usually not included. Following the contributing steps, I noticed that the tests failed after making my changes. I started investigating whether my changes broke the code, and later, I realized that the tests failed because I forked the repository without tags. For this reason, I decided to change the order of operations in contributing.md file to build and run tests before making any changes to verify the initial state. I hope the improved contributing guide will help other contributors …
=> docs(contributing): mention fetching the tags for running tests successfully

git-cliff-core/src/repo.rs
Apply [unnested_or_patterns](https://rust-lang.github.io/rust-clippy/master/index.html#/unnested_or_patterns) clippy lint from the pedantic group.
I also apply those changes to get more familiar with the project and later I will take some of the open issues.
Command:
```sh
cargo …
```
=> refactor(clippy): apply unnested_or_patterns clippy lint

git-cliff-core/src/changelog.rs, git-cliff-core/src/commit.rs, git-cliff-core/src/remote/gitlab.rs, git-cliff-core/src/template.rs, git-cliff/src/args.rs, git-cliff/src/lib.rs
Apply [semicolon_if_nothing_returned](https://rust-lang.github.io/rust-clippy/master/index.html#/semicolon_if_nothing_returned) clippy lint from the pedantic group.
I use the `refactor(clippy)` format for my commits, which is omitted from the changelog report. 
I also apply those changes to get more familiar with the project and later I will take some of the open issues. …
=> refactor(clippy): apply semicolon_if_nothing_returned clippy lint

git-cliff-core/src/changelog.rs, git-cliff-core/src/commit.rs
Apply [option_as_ref_cloned](https://rust-lang.github.io/rust-clippy/master/index.html#/option_as_ref_cloned) clippy lint from the pedantic group.
I also apply those changes to get more familiar with the project and later I will take some of the open issues.
Command:
```sh
cargo …
```
=> refactor(clippy): apply option_as_ref_cloned lint

git-cliff-core/src/embed.rs
Apply [case_sensitive_file_extension_comparisons](https://rust-lang.github.io/rust-clippy/master/index.html#/case_sensitive_file_extension_comparisons) clippy lint from the pedantic group.
I also apply those changes to get more familiar with the project and later I will take some of the open issues.
I ran the specific lint checks and solved the problem until the linter no longer …
=> refactor(clippy): apply case_sensitive_file_extension_comparisons lint

git-cliff/src/lib.rs
Now we support the following use case:
```sh
$ git cliff --unreleased --tag 1.2.3 --tag-message "Release 1.2.3"
```
closes #836
Locally.
=> fix(changelog): correctly set the tag message for the latest release

git-cliff-core/src/changelog.rs
Apply [manual_is_variant_and](https://rust-lang.github.io/rust-clippy/master/index.html#/manual_is_variant_and) clippy lint from the pedantic group.
Command:
```sh
cargo clippy --all-targets -- -D warnings -W clippy::manual_is_variant_and
```
=> refactor(clippy): apply manual_is_variant_and lint

git-cliff-core/src/changelog.rs, git-cliff-core/src/config.rs
Apply [explicit_iter_loop](https://rust-lang.github.io/rust-clippy/master/index.html#/explicit_iter_loop) clippy lint from the pedantic group.
Note: We already use that notation in other places. Example in the lib.rs:
```rust
for release in &mut releases {...
```
Command:
```sh …
```
=> refactor(clippy): apply explicit_iter_loop lint

git-cliff/src/lib.rs
There is no need to warn about template when `--bumped-version` argument is being used.
closes #846
Locally.
=> fix(bump): suppress template warning when `--bumped-version` is used

git-cliff-core/src/commit.rs
Now we remove the trailing newline for every commit retrieved from a repository.
closes #745
`cargo test`
=> fix(commit): trim the trailing newline for git2 commits

.github/workflows/ci.yml
Add pedantic lints checking to the CI and do not fail the CI if warnings exist.
It is good to have some reports about pedantic errors at the merging level, especially in pull requests. Now, users can see the quality of their code on a pedantic linter level. 
We are currently resolving many pedantic errors in the existing code in the other MR.
I tested the command manually in the terminal.
I tested the CI in that pull request. If the build passes and we have an extra step in the Lints job with pedantic warnings, that means we have configured the CI correctly.
=> chore(ci): check pedantic lints

git-cliff/src/args.rs, npm/git-cliff/eslint.config.js, npm/git-cliff/package.json, npm/git-cliff/src/options.ts, npm/git-cliff/src/optionsToStringArgs.ts, npm/git-cliff/yarn.lock, website/docs/usage/args.md
> [!WARNING]
> **_This should be merged with "rebase & merge" to retain proper conventional commit history for the changelog generation_**
Couple of changes bundled:
- I got the request to implement `skip-commit` in cliff-jumper. Because the appropriate syntax for `git-cliff` is `--skip-commit SHA --skip-commit SHA --skip-commit SHA --skip-commit SHA <options options>` it is more ideal if the NodeJS code optionally takes an array of commits which can easily be parsed to CLI args in the library as opposed to janking something in cliff-jumper.
- I noticed some options from https://git-cliff.org/docs/usage/args were missing in the `Options` type so I added them.
- While doing the above I also decided to copy over all the descriptions for all the options to TSDoc comments so they are …
=> NPM option parsing improvements and documentation improvements

cliff.toml, config/cliff.toml, git-cliff-core/src/changelog.rs, git-cliff-core/src/config.rs, git-cliff-core/tests/integration_test.rs, git-cliff/src/lib.rs, website/docs/configuration/changelog.md
This PR adds a new configuration option as follows:
```toml
[changelog]
output = "CHANGELOG.md"
```
It does not take precedence over command-line arguments which means you can override it with the `--output` option.
closes #827
Locally.
=> feat(config): allow configuring output file from config

.github/fixtures/test-always-render/expected.md, website/blog/git-cliff-2.5.0.md, website/blog/git-cliff-2.6.0.md, website/docusaurus.config.js
=> docs(website): add highlights for 2.6.0

git-cliff-core/src/commit.rs, git-cliff-core/src/config.rs
Apply [single_match_else](https://rust-lang.github.io/rust-clippy/master/index.html#/single_match_else) clippy lint from the pedantic group.
Command:
```sh
cargo clippy --all-targets -- -D warnings -W clippy::single_match_else
```
=> refactor(clippy): apply single_match_else lint

git-cliff-core/src/commit.rs, git-cliff/src/lib.rs
Apply [assigning_clones](https://rust-lang.github.io/rust-clippy/master/index.html#/assigning_clones) clippy lint from the pedantic group.
Command:
```sh
cargo clippy --all-targets -- -D warnings -W clippy::assigning_clones
```
=> refactor(clippy): apply assigning_clones lint

npm/git-cliff/eslint.config.js, npm/git-cliff/package.json, npm/git-cliff/src/options.ts, npm/git-cliff/yarn.lock
v2.6.0 introduced `--use-branch-tags` but that flag wasn't added to the TS types. Kinda awkward when the changelog specifically says that TS types are fixed ;)
Adding the missing option
N.A., types only
=> fix(npm): add missing `--use-branch-tags` flag to TS options

git-cliff-core/src/changelog.rs, git-cliff-core/src/commit.rs, git-cliff-core/src/repo.rs
Apply [if_not_else](https://rust-lang.github.io/rust-clippy/master/index.html#/if_not_else) clippy lint from the pedantic group.
Command:
```sh
cargo clippy --all-targets -- -D warnings -W clippy::if_not_else
```
=> refactor(clippy): apply if_not_else lint

.github/actions/run-fixtures-test/action.yml
Should speed up CI since every fixture test builds its own git-cliff binary; an alternative would be to have a separate job that installs the binary and make all the fixture jobs depend on it.
=> chore(fixtures): build binaries using dev profile

website/docs/tips-and-tricks.md
Using `pandoc` as separate command, the markdown output can be converted to pdf
If you need to share the changelog as pdf this could be handy
=> docs(website): add conversion to pdf to tips-and-tricks

.github/fixtures/test-bitbucket-integration/cliff.toml, .github/fixtures/test-bitbucket-integration/commit.sh, .github/fixtures/test-bitbucket-integration/expected.md, git-cliff-core/src/release.rs, git-cliff-core/src/remote/bitbucket.rs, git-cliff-core/src/remote/mod.rs
Fixes Bitbucket pull request matching to release metadata:
- update BitbucketPullRequest struct to use merge_commit
- update metadata matching to support short sha format
- add tests for Bitbucket remote
When testing the Bitbucket integration the pull request matching does not work. Commits are not being matched to pull requests looking into the API response it looks to be for two reasons
Fixes #905
```bash
git clone git@bitbucket.org:mcwarman-playground/playground.git
cd playground
~/code/src/github.com/orhun/git-cliff/target/debug/git-cliff --current --context --bitbucket-repo "mcwarman-playground/playground" | jq .
```
=> fix(bitbucket): match PR and release metadata correctly

git-cliff-core/src/repo.rs
This is a small change to get my feet wet and add some unit tests.
See #658.
Unit tests.
=> test(repo): expand unit tests of the repo module

.dockerignore, .github/workflows/docker.yml
Enable the arm64 image creation again in the docker workflow. 
The arm64 image builds were previously disabled because they ran into timeouts.
The cause seemed to be, that cargo-chef accidentally build the dependencies twice. And the second build managed to hit the timeout. This solves this, by no longer using the toolchain specified in rust-toolchain.toml but instead relying on the already installed rust version from the image.
This speeds up the build twice:
- No longer building the dependencies twice
- No longer installing the nightly rust toolchain twice
This should fix #879 and make #888 no longer needed.
I have tested this on my fork by changing the workflow in a way that it only builds but does not push.
In this [commit](https://github.com/LtdSauce/git-cliff/commit/40905f063724af0cc …
=> feat(docker): build arm64 images again (#879)

CONTRIBUTING.md, git-cliff-core/src/repo.rs
When looking for the `owner` and `repo` of the remote for the current `HEAD`, we will now try to parse the SSH format of a remote if it fails to match an HTTPS format of a remote.
When the `git-cliff` repo is cloned for development using the SSH protocol, the test `repo::test::git_upstream_remote` fails.
The `upstream_remote` function was relying on `url::Url::parse` to extract the `owner` and `repo` from the `url`. But that only works when the repo is cloned using HTTPS, e.g. `https://github.com/orhun/git-cliff.git`. However, this would fail to parse when cloned using SSH, e.g. `git@github.com:orhun/git-cliff.git`.
Now, if the `url::URL::parser` fails, we now try to parse an SSH remote in the format `git@hostname:owner/repo.git`.
The error from `upstream_remote` also notes that a …
=> test(git): find upstream remote when using ssh

git-cliff-core/tests/integration_test.rs
Moves the creation of an array of `TextProcessor` objects, that includes the contruction of a `Regex` to the outside of a loop. The array is only ever user by reference, so reusing a single instance will produce the same effects.
The Lints CI check is failing due to the creation of the same Regex within a loop.
The change is within the integration tests, and those continue to pass.
=> fix: don't create regex inside a loop

git-cliff-core/src/repo.rs, website/docs/usage/jujutsu.md
Adds support for opening the Git repository used when a repository is cloned using Jujutsu and the `--colocate` option was *NOT* used.
Note: this requires that the user updates the `HEAD` of the git repository to point to their mainline branch, as the Git repository the Jujutsu creates isn't 100% configured.
If the .git directory can't be opened (usually because the `.git` directory is missing) it attempts to find the git repository in the location used by Jujutsu (i.e. `.jj/repo/store/git`). If the Jujutsu git directory doesn't exist, then the origin error is propogated.
Jujutsu is a Version Control System that uses Git as it's local store, and can work as an effective replacement for Git on a Developer's workstation.
When a Git repository is cloned by Jujutsu, the default location for …
=> feat: jujustu support

website/blog/git-cliff-2.6.0.md, website/blog/git-cliff-2.7.0.md, website/docusaurus.config.js
=> docs(website): add highlights for 2.7.0

website/docs/tips-and-tricks.md
Updated Tip and Tricks docs based on the answer provided in #143 
The docs were wrong
The code itself I tested myself in a default toml config file.
=> Update docs based on #143

git-cliff-core/src/remote/gitlab.rs
`GitLabMergeRequest::merge_commit()` now returns the commit's sha instead of `None` if the Merge Request was not merged using a merge commit but with fast-forward. 
In the generation of the changelog commits were not linked to their GitLab MR if the commit was merged using fast-forward.
This change allows to identify the corresponding GitLab MR independently if the MR was merged with a merge commit or with fast-forward.
Existing tests are sufficient and still pass.
=> fix(remote) Fix detection of GitLab merge request sha

git-cliff-core/src/repo.rs
`git-cliff` now _discovers_ the Git repositories automatically even though when you run from sub directories.
See #969
Closes #426
Locally.
=> feat(repo): allow running from sub directories

git-cliff-core/src/error.rs, git-cliff-core/src/repo.rs
Before:
```
>_ orhun ζ git cliff test
ERROR git_cliff > Git error: `unable to parse OID - contains invalid characters; class=Invalid (3)`
```
After:
```
>_ orhun ζ git cliff test
ERROR git_cliff > Failed to set the commit range: unable to parse OID - contains invalid characters; class=Invalid (3)
"test" is not a valid commit range. Did you provide the correct arguments?
```
see #986
Locally.
=> feat(git): improve the set commit range error

git-cliff/src/lib.rs, website/docs/usage/examples.md, website/docs/usage/initializing.md
Allow user to define init file by passing `--config` alongside to `--init` 
closes #932 
Ran locally using `--init` and `--config` flags together as well as separate to make sure there where no breaking changes
=> feat(cli): add synergy between init and config flags

git-cliff/src/lib.rs
=> fix(monorepo): do not set include-path if workdir is set

website/blog/git-cliff-2.7.0.md, website/blog/git-cliff-2.8.0.md, website/docusaurus.config.js
=> docs(website): add highlights for 2.8.0

git-cliff-core/src/remote/gitlab.rs
`GitLabMergeRequest::merge_commit()` now returns the `squash_commit_sha` instead of None if the commits where squashed in the Merge Request.
In the generation of the changelog commits were not linked to their GitLab MR if the commits were squashed.
This change allows to identify the corresponding GitLab MR independently if the commit in the MR were squashed or not.
Unittest added.
=> fix(remote): Fix detection of GitLab merge request sha if commits were squashed

git-cliff-core/src/repo.rs, git-cliff/src/lib.rs
Now we take worktrees into account while retrieving the path of the repositories.
Closes #1052
Locally.
=> fix(git): handle worktrees while retrieving the path of repository

git-cliff-core/src/command.rs
Fixes the following linter error:
```
error: this can be `std::io::Error::other(_)`
--> git-cliff-core/src/command.rs:46:4
|
46 |             IoError::new(IoErrorKind::Other, "stdin is not captured")
|             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#io_other_error
= note: `-D clippy::io-other-error` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::io_other_error)]`
help: use `std::io::Error::other`
|
46 -             IoError::new(IoErrorKind::Other, "stdin is not captured")
46 +             IoError::other("stdin is not captured")
|
error: this can be `std::io::Error::other(_)`
--> git-cliff-core/src/command.rs:64:7
|
64 | …
```
=> refactor: use IOError::other

README.md
See https://github.com/orhun/git-cliff-action/issues/49#issuecomment-2732013691
=> docs(readme): add blog posts from the community

git-cliff-core/src/config.rs
`bump_type` was intended to be used lowercase and that's what we suggest in the docs. However the implementation says otherwise.
Basically fixes that issue.
See https://github.com/orhun/git-cliff/issues/1066#issuecomment-2738069069
Not tested, I believe in myself.
=> fix(bump): accept lowercase values for bump_type config

.github/actions/run-fixtures-test/action.yml, .github/fixtures/test-require-conventional-skipped/cliff.toml, .github/fixtures/test-require-conventional-skipped/commit.sh, .github/fixtures/test-require-conventional-skipped/expected.md
Fixes the test fixtures for #1061.
#1061 changed the fixtures system to allow checking git-cliff's return code. This unintentionally broke all fixtures. The problem was caused by GitHub running all bash scripts with `set -e` by default, leading to any failing command failing the entire script. I circumvented this by appending the git-cliff command with `|| true`, thereby breaking the subsequent checks.
This PR fixes the problem by adding `set +e` prior to running git-cliff, thus allowing evaluation of its rc as intended.
Additionally it fixes the fixture `test-require-conventional-skipped`. This fixture never worked right, but was deemed successful due to the bug.
Running fixtures locally and in GitHub actions.
=> fix(fixtures): evaluate the rc of git-cliff correctly

git-cliff/src/lib.rs
Check the next version against the regex set by `--tag-pattern` when bumping versions.
closes #1066
Locally.
=> fix(bump): check the next version against tag_pattern regex

Dockerfile, flake.lock, git-cliff-core/Cargo.toml, git-cliff-core/src/commit.rs, git-cliff-core/src/config.rs, git-cliff-core/src/remote/mod.rs, git-cliff-core/src/repo.rs, git-cliff-core/src/template.rs, git-cliff/Cargo.toml, git-cliff/src/args.rs, git-cliff/src/lib.rs, git-cliff/src/logger.rs, git-cliff/src/main.rs, rustfmt.toml
Migrates the codebase to Rust 2024 edition, see <https://blog.rust-lang.org/2025/02/20/Rust-1.85.0/>
MSRV is now 1.85.0
I'm always on the edge.
Locally.
=> chore(project): migrate to Rust 2024 edition

website/docs/configuration/git.md
This PR fixes a tiny typo, `commits.links` should be `commit.links`.
I just found this tiny typo when editing the `body` template.
- [x ] I have updated the documentation accordingly.
=> doc(config): fix typo on commit.links

git-cliff-core/src/commit.rs
Fixes inconsistent serde_json::Value string representations when applying regex matchers. Specifically, it ensures that:
- `Value::String` does not include surrounding quotes,
- other scalar types (`Number`, `Bool`, `Null`) are stringified appropriately,
- `Object` and `Array` are treated as unsupported and result in an error.
Closes #1143 
Previously, `serde_json::Value::String("example")` was converted using `to_string()`, resulting in `"\"example\""`, which broke regex patterns expecting plain strings. This PR fixes that by:
- Matching and extracting raw strings for `Value::String`,
- Applying `to_string()` to `Number`, `Bool`, and `Null`,
- Raising a user-friendly error if the field is an `Object` or `Array`.
This makes pattern matching robust and predictable when working with JSON …
=> fix(template): correctly serialize JSON for the commit fields

.github/fixtures/test-commit-footers/cliff.toml, examples/detailed.toml
Check if the `commit.footers` array was defined in the body template. An alternative would be to always pass `commit.footers` and empty if there are no footers. I don't have enough Rust knowledge to make that change related to https://github.com/orhun/git-cliff/pull/97.
The change is required to fix a bug in `examples/detailed.toml`. That configuration assumes that all the commits will have a footer. This is a bug when rendering the `body` template because sometimes there could be commits without footers because the PR author merged without a footer. 
Creating a `detailed.toml` configuration in my private repository and applying the fix.
Variable `commit.footers` not found in context while rendering 'body'
=> fix: check if commit.footers is defined in detailed example

website/docs/integration/bitbucket.md, website/docs/integration/gitea.md, website/docs/integration/github.md, website/docs/integration/gitlab.md
The text says that the extra information is added in a `gitea` nested object, but it's in fact a `remote` object according to the examples.
=> doc: Fix inconsistency in documentation of Gitea integration

git-cliff/src/lib.rs
Base path is second parameter of `pathdiff::diff_paths`.
_Partially_ f*xes #1187 
Just vibes
```
cargo run -- --repository ../ratatui ../mousefood
```
Before:
```
INFO  git_cliff > Including changes from the current directory: "../git-cliff"
INFO  git_cliff > Including changes from the current directory: "../git-cliff"
```
After:
```
INFO  git_cliff > Including changes from the current directory: "../ratatui"
INFO  git_cliff > Including changes from the current directory: "../mousefood"
```
=> fix(log): display correct repository paths in log

.github/actions/run-fixtures-test/action.yml, .github/fixtures/test-release-statistics/cliff.toml, .github/fixtures/test-release-statistics/commit.sh, .github/fixtures/test-release-statistics/expected.md, .github/workflows/test-fixtures.yml, Cargo.lock, git-cliff-core/Cargo.toml, git-cliff-core/src/changelog.rs, git-cliff-core/src/commit.rs, git-cliff-core/src/lib.rs, git-cliff-core/src/release.rs, git-cliff-core/src/remote/mod.rs, git-cliff-core/src/statistics.rs, git-cliff-core/src/template.rs, git-cliff-core/tests/integration_test.rs, git-cliff/src/lib.rs, website/docs/templating/context.md
This adds support for computing and exposing aggregated commit statistics:
- Total number of commits
- Duration (in days) between the first and last commit
- Number of conventional commits
- Link references and their counts
- Days since the previous release
The data is accessible in templates using the {{ statistics }} variable.
- The core logic is located in [`Release::aggregate_statistics`](https://github.com/orhun/git-cliff/blob/63c3fea6efc7233d25544887be6d78f3c3509b09/git-cliff-core/src/release.rs#L244).
- The aggregation is performed based on the snapshot of `commits` at the time of execution.
- Statistics are computed after `Changelog::process_commits`, meaning they reflect the state of commits after they have been split, filtered, and transformed (e.g., via `into_conventional` …
=> feat: add commit statistics to the changelog

.github/fixtures/test-skip-tags/cliff.toml, .github/fixtures/test-skip-tags/commit.sh, .github/fixtures/test-skip-tags/expected.md, git-cliff-core/src/changelog.rs
This PR refactors the logic that determines whether to skip a tag during changelog generation.
Previously, some skip conditions were nested or not independently evaluated.
Now, all conditions are flattened and evaluated, making the behavior more predictable and consistent.
The prior implementation may have skipped tags inconsistently if some conditions short-circuited the evaluation.
Fixes or relates to: #1181 
- Added a test fixture.
N/A
=> fix: ensure skip_tags condition is evaluated first

.github/workflows/ci.yml, git-cliff-core/src/changelog.rs, git-cliff-core/src/command.rs, git-cliff-core/src/commit.rs, git-cliff-core/src/config.rs, git-cliff-core/src/contributor.rs, git-cliff-core/src/embed.rs, git-cliff-core/src/error.rs, git-cliff-core/src/lib.rs, git-cliff-core/src/release.rs, git-cliff-core/src/remote/bitbucket.rs, git-cliff-core/src/remote/gitea.rs, git-cliff-core/src/remote/github.rs, git-cliff-core/src/remote/gitlab.rs, git-cliff-core/src/remote/mod.rs, git-cliff-core/src/repo.rs, git-cliff-core/src/statistics.rs, git-cliff-core/src/tag.rs, git-cliff-core/src/template.rs, git-cliff-core/tests/integration_test.rs, git-cliff/examples/run.rs, git-cliff/src/args.rs, git-cliff/src/bin/completions.rs, git-cliff/src/bin/mangen.rs, git-cliff/src/lib.rs, git-cliff/src/logger.rs, git-cliff/src/main.rs, git-cliff/src/profiler.rs, rust-toolchain.toml, rustfmt.toml
chore: update formatting rules
Use spaces instead of tabs for indentation, wrap at 100 characters, and
remove the setting that aligns struct fields vertically as this
generally harms readability.
These changes make the code more consistent with the Rust community's
conventions and improve readability by not truncating lines too early.
---
Justification:
https://www.youtube.com/watch\?v\=V7PLxL8jIl8
This brings things more in line with pretty much every rust project out there. Hard tabs are used in around 0.1% of rust projects:
- `hard_tabs = true`: https://github.com/search?q=path%3A%22rustfmt.toml%22+%22hard_tabs+%3D+true%22+AND+%28NOT+is%3Afork%29&type=code (1.9k results)
- projects with a rustfmt.toml: https://github.com/search?q=path%3A%22rustfmt.toml%22+AND+%28NOT+is%3Afork%29&type=co …
=> style: update formatting rules

npm/git-cliff/package.json, npm/git-cliff/src/index.ts, npm/git-cliff/tsconfig.json, npm/git-cliff/tsup.config.ts, npm/git-cliff/yarn.lock
This updates execa to v9 properly, unlike #1211.
Requested by Orhun in discord DM
`yarn typecheck` and `yarn build`
=> fix: execa update to v9

examples/keepachangelog.toml
In the `keepachangelog` config template, if there is not a prior tag, then link the first tag to the tree at that tag instead of not emitting a link at all.
This fixes the first release version in the `keepachangelog` format not being linkified.
I ran this against a test repo locally.
=> fix(config): link to tree for first tag

git-cliff-core/src/config.rs, git-cliff/src/lib.rs
git-cliff ignores the `XDG_CONFIG_HOME` env var on macOS and only considers `Library/Application Support` as the config dir, which is primarily used by GUI apps.
This change allows the default config file to be placed in the following 3 locations on macOS:
- `XDG_CONFIG_HOME/git-cliff/cliff.toml`
- `~/.config/git-cliff/cliff.toml`
- `~/Library/Application Support/git-cliff/cliff.toml`
The first one found is used.
see https://github.com/orhun/git-cliff/pull/1249#issuecomment-3301875097
manually and with debug output
=> feat(cli): honor XDG_CONFIG_HOME on macOS

git-cliff/src/args.rs, website/docs/usage/args.md
Added `help_heading = "REMOTE OPTIONS"` to all remote-related CLI arguments (`--github-token`, `--github-repo`, `--gitlab-token`, `--gitlab-repo`, `--gitea-token`, `--gitea-repo`, `--bitbucket-token`, `--bitbucket-repo`) to group them under a dedicated "REMOTE OPTIONS" section in the help output. 
Fixes #1270
- Built the project successfully using `cargo build`
- Ran `git-cliff -h` to verify the help output shows the new "REMOTE OPTIONS" section
- Confirmed all remote arguments are properly grouped under the new heading
- Ran `cargo test` to ensure CLI argument parsing tests pass (the `verify_cli` test validates the argument structure)
=> feat: group remote-related CLI arguments under REMOTE OPTIONS heading
